"""US option market-data adapter backed only by the official ``hs`` SDK."""

import logging
import os
import re
import threading
from concurrent.futures import ThreadPoolExecutor, as_completed
from typing import Optional


# The installed HS SDK ships protobuf files generated by an older protoc.
# This must be set before importing hs under modern protobuf versions.
os.environ.setdefault("PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION", "python")

try:
    import hs  # noqa: F401 - explicit SDK dependency and availability check
    from hs.api.hq_constant import DataType, MktTmType, OptionType
    from hs.api.hs_open_api import OpenAPI

    SDK_AVAILABLE = True
    SDK_IMPORT_ERROR = None
except Exception as exc:  # pragma: no cover - depends on local SDK installation
    DataType = None
    MktTmType = None
    OptionType = None
    OpenAPI = None
    SDK_AVAILABLE = False
    SDK_IMPORT_ERROR = exc


logger = logging.getLogger(__name__)


class HSOptionAPIError(RuntimeError):
    """Raised when the SDK or HS Gateway cannot serve an option request."""


def _as_float(value, default=0.0):
    try:
        number = float(value)
        return number if number == number else default
    except (TypeError, ValueError):
        return default


def _as_int(value, default=0):
    try:
        return int(float(value))
    except (TypeError, ValueError):
        return default


class HSOptionMarketData:
    """Read-only option-chain service using :class:`hs.api.OpenAPI` methods."""

    def __init__(self, ip=None, http_port=None, tcp_port=None, open_api=None):
        if open_api is None and not SDK_AVAILABLE:
            raise HSOptionAPIError(f"华盛 HS SDK 不可用: {SDK_IMPORT_ERROR}")

        self.ip = ip or os.getenv("HUASHENG_GATEWAY_IP", "127.0.0.1")
        try:
            self.http_port = int(http_port or os.getenv("HUASHENG_HTTP_PORT", "11111"))
            self.tcp_port = int(tcp_port or os.getenv("HUASHENG_TCP_PORT", "11112"))
        except (TypeError, ValueError) as exc:
            raise HSOptionAPIError("华盛 Gateway 端口必须是整数") from exc

        self._open_api = open_api or OpenAPI(
            ip=self.ip,
            http_port=self.http_port,
            tcp_port=self.tcp_port,
            logging_filename=os.getenv("HUASHENG_OPTION_SDK_LOG"),
        )
        # The SDK's HTTP request path is synchronous. Serialize access so the
        # shared backend instance remains predictable under concurrent clicks.
        self._lock = threading.RLock()

    @staticmethod
    def _data(response, operation):
        if not isinstance(response, dict) or not response.get("ok"):
            detail = response.get("err") if isinstance(response, dict) else response
            raise HSOptionAPIError(f"{operation}失败: {detail or 'HS Gateway 无响应'}")
        data = response.get("data")
        return data if isinstance(data, dict) else {}

    @staticmethod
    def _clean_symbol(symbol):
        return (
            str(symbol or "").strip().upper()
            .replace("US.", "")
            .replace(".US", "")
        )

    def _basic_quotes(self, codes, data_type, batch_size=50):
        unique_codes = list(dict.fromkeys(str(code).strip().upper() for code in codes if code))
        quotes = []
        for start in range(0, len(unique_codes), batch_size):
            batch = unique_codes[start:start + batch_size]
            response = self._open_api.query_hq_basic_qot(
                security_list=[
                    {"dataType": data_type, "code": code}
                    for code in batch
                ],
                mkt_tm_type=MktTmType.MID_SESSION,
            )
            data = self._data(response, "查询基础报价")
            quotes.extend(data.get("basicQot") or [])
        return quotes

    def _order_book_snapshot(self, code):
        """Fetch the best bid/ask for one HS option contract."""
        try:
            response = self._open_api.query_hq_order_book(
                security_param={"dataType": DataType.US_OPTION, "code": code},
                mkt_tm_type=MktTmType.MID_SESSION,
            )
            data = self._data(response, f"查询 {code} 买卖盘")
            bids = data.get("orderBookBidList") or []
            asks = data.get("orderBookAskList") or []
            best_bid = max(bids, key=lambda item: _as_float(item.get("price")), default={})
            positive_asks = [item for item in asks if _as_float(item.get("price")) > 0]
            best_ask = min(positive_asks, key=lambda item: _as_float(item.get("price")), default={})
            bid = _as_float(best_bid.get("price"))
            ask = _as_float(best_ask.get("price"))
            return code, {
                "bid": bid,
                "ask": ask,
                "bid_size": _as_int(best_bid.get("volume")),
                "ask_size": _as_int(best_ask.get("volume")),
                "mid": (bid + ask) / 2 if bid > 0 and ask > 0 else 0.0,
            }
        except Exception as exc:
            logger.debug("HS option order book unavailable for %s: %s", code, exc)
            return code, {}

    def _order_books(self, codes, max_workers=8):
        """Fetch independent order books concurrently to keep the chain responsive."""
        snapshots = {}
        with ThreadPoolExecutor(max_workers=min(max_workers, max(1, len(codes)))) as executor:
            futures = [executor.submit(self._order_book_snapshot, code) for code in codes]
            for future in as_completed(futures):
                code, snapshot = future.result()
                snapshots[code.upper()] = snapshot
        return snapshots

    def _underlying_quote(self, symbol):
        for data_type in (DataType.US_STOCK, DataType.US_ETF):
            try:
                quotes = self._basic_quotes([symbol], data_type)
            except HSOptionAPIError:
                quotes = []
            if quotes:
                return quotes[0]
        raise HSOptionAPIError(f"找不到 {symbol} 的正股行情")

    def get_expirations(self, symbol):
        symbol = self._clean_symbol(symbol)
        with self._lock:
            response = self._open_api.query_hq_us_option_chain_expire_date(
                stock_code=symbol,
            )
        data = self._data(response, "查询期权到期日")
        return [str(value) for value in data.get("expireDate") or [] if value]

    def _get_codes(self, symbol, expiration, option_type):
        response = self._open_api.query_hq_us_option_chain_code(
            stock_code=symbol,
            expire_date=expiration,
            option_type=option_type,
        )
        data = self._data(response, "查询期权合约代码")
        return [str(value) for value in data.get("optionCode") or [] if value]

    @staticmethod
    def _contract_strike(symbol, code):
        """Parse the HS code suffix: root + yymmdd + C/P + strike*10000."""
        suffix = str(code).upper()[len(symbol):]
        match = re.fullmatch(r"\d{6}[CP](\d+)", suffix)
        return int(match.group(1)) / 10000 if match else None

    @classmethod
    def _near_money_codes(cls, symbol, codes, spot_price, limit):
        def distance(code):
            strike = cls._contract_strike(symbol, code)
            return abs(strike - spot_price) if strike is not None else float("inf")

        return sorted(codes, key=distance)[:limit]

    @staticmethod
    def _normalize_contract(raw, fallback_code, option_type, expiration):
        security = raw.get("security") or {}
        option_data = raw.get("optionExData") or {}
        code = security.get("code") or raw.get("code") or fallback_code
        last = _as_float(raw.get("lastPrice"))
        return {
            "contract_symbol": code,
            "option_type": option_type,
            "expiration": option_data.get("expireDate") or expiration.replace("/", ""),
            "strike": _as_float(option_data.get("strikePrice")),
            "last": last,
            "mark": last,
            "open": _as_float(raw.get("openPrice")),
            "high": _as_float(raw.get("highPrice")),
            "low": _as_float(raw.get("lowPrice")),
            "previous_close": _as_float(raw.get("lastClosePrice")),
            "volume": _as_int(raw.get("volume") or raw.get("volumeStr")),
            "open_interest": _as_int(option_data.get("openInterest")),
            "implied_volatility": _as_float(option_data.get("iv")),
            "delta": _as_float(option_data.get("delta")),
            "gamma": _as_float(option_data.get("gamma")),
            "vega": _as_float(option_data.get("vega")),
            "theta": _as_float(option_data.get("theta")),
            "rho": _as_float(option_data.get("rho")),
            "intrinsic_value": _as_float(option_data.get("intrinsicValue")),
            "time_value": _as_float(option_data.get("timeValue")),
            "actual_leverage": _as_float(option_data.get("actualLeverage")),
            "trade_time": raw.get("tradeTime") or raw.get("marketTime"),
        }

    def get_chain(self, symbol, expiration: Optional[str] = None, contracts_per_side=12):
        symbol = self._clean_symbol(symbol)
        with self._lock:
            expirations = self.get_expirations(symbol)
            if not expirations:
                raise HSOptionAPIError(f"{symbol} 没有可用期权到期日")
            selected_expiration = expiration or expirations[0]
            if selected_expiration not in expirations:
                raise HSOptionAPIError(f"到期日 {selected_expiration} 不在当前期权链中")

            call_codes = self._get_codes(symbol, selected_expiration, OptionType.CALL)
            put_codes = self._get_codes(symbol, selected_expiration, OptionType.PUT)
            total_call_contracts = len(call_codes)
            total_put_contracts = len(put_codes)
            underlying = self._underlying_quote(symbol)
            last_price = _as_float(underlying.get("lastPrice"))
            call_codes = self._near_money_codes(
                symbol, call_codes, last_price, contracts_per_side
            )
            put_codes = self._near_money_codes(
                symbol, put_codes, last_price, contracts_per_side
            )
            option_quotes = self._basic_quotes(
                call_codes + put_codes,
                DataType.US_OPTION,
            )
            order_books = self._order_books(call_codes + put_codes)

        quotes_by_code = {}
        for quote in option_quotes:
            security = quote.get("security") or {}
            code = security.get("code") or quote.get("code")
            if code:
                quotes_by_code[str(code).upper()] = quote

        calls = [
            {
                **self._normalize_contract(
                    quotes_by_code.get(code.upper(), {}), code, "call", selected_expiration
                ),
                **order_books.get(code.upper(), {}),
            }
            for code in call_codes
        ]
        puts = [
            {
                **self._normalize_contract(
                    quotes_by_code.get(code.upper(), {}), code, "put", selected_expiration
                ),
                **order_books.get(code.upper(), {}),
            }
            for code in put_codes
        ]
        calls.sort(key=lambda item: item["strike"])
        puts.sort(key=lambda item: item["strike"])

        previous_close = _as_float(underlying.get("lastClosePrice"))
        change = last_price - previous_close if previous_close else 0.0
        return {
            "symbol": symbol,
            "name": (
                underlying.get("name")
                or underlying.get("nameCh")
                or underlying.get("stockName")
                or symbol
            ),
            "currency": "USD",
            "market_price": last_price,
            "market_change": change,
            "market_change_percent": (change / previous_close * 100) if previous_close else 0.0,
            "quote_time": underlying.get("tradeTime") or underlying.get("marketTime"),
            "expiration": selected_expiration,
            "expirations": expirations,
            "calls": calls,
            "puts": puts,
            "total_call_contracts": total_call_contracts,
            "total_put_contracts": total_put_contracts,
            "chain_scope": "near_money",
            "source": "HS SDK",
            "data_type": DataType.US_OPTION,
        }
